version: "3.9"

services:
  spring:
    build:
      context: ./
      dockerfile: src/Dockerfile
    container_name: spring
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: ${DATABASE_NAME:-cinemaapi}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-admin}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      MINIO_URL: ${MINIO_URL:-http://localhost:9000}
      MINIO_RESPONSE: ${MINIO_RESPONSE:-http://localhost:9000}
      MINIO_USERNAME: ${MINIO_USERNAME:-minioadmin}
      MINIO_PASSWORD: ${MINIO_PASSWORD:-minioadmin}
      MINIO_BUCKET: ${MINIO_BUCKET:-cinema}
      JWT_SECRET: ${JWT_SECRET:-palavrasecreta}
    networks:
      - public_network
    restart: always

volumes:
  data:

networks:
  public_network:
    driver: bridge
