spring:
  application:
    name: cinema-api

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:interchange.proxy.rlwy.net}:${POSTGRES_PORT:52329}/${DATABASE_NAME:railway}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:UTOhPwlefxdExGEkJAsoAKWLcBSlyTaO}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

minio:
  url: ${MINIO_URL:https://miniosatccinema.up.railway.app}
  access-key: ${MINIO_USERNAME:minio}
  secret-key: ${MINIO_PASSWORD:minio123}
  bucket: ${MINIO_BUCKET:cinema}
  response: ${MINIO_RESPONSE:https://miniosatccinema.up.railway.app}
