server:
  address: 0.0.0.0
  port: ${BACKEND_PORT:8080}

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  application:
    name: cinema-api

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

minio:
  url: ${MINIO_URL:https://miniolegal.com}
  access-key: ${MINIO_USERNAME:minio}
  secret-key: ${MINIO_PASSWORD:minio123}
  bucket: ${MINIO_BUCKET:cinema}
  response: ${MINIO_RESPONSE:https://miniolegal.com}

api:
  jwt:
    secretKey:
      token: ${JWT_SECRET:digitesuachaveaqui}
