spring:
  application:
    name: cinema-api

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:postgres}:${POSTGRES_PORT:5432}/${DATABASE_NAME:cinemaapi}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_USERNAME:minioadmin}
  secret-key: ${MINIO_PASSWORD:minioadmin}
  bucket: ${MINIO_BUCKET:cinema-bucket}
  response: ${MINIO_RESPONSE:http://localhost:9000}
