spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: cinema-api

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:host}:${POSTGRES_PORT:5432}/${DATABASE_NAME:cinema}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:senha}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

minio:
  url: ${MINIO_URL:https://miniolegal.com}
  access-key: ${MINIO_USERNAME:minio}
  secret-key: ${MINIO_PASSWORD:minio123}
  bucket: ${MINIO_BUCKET:cinema}
  response: ${MINIO_RESPONSE:https://miniolegal.com}

api:
  jwt:
    secretKey:
      token: ${JWT_SECRET:digitesuachaveaqui}